spring.application.name=backend

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/sdetcommerce
spring.datasource.username=sdetuser
spring.datasource.password=sdetpassword

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true